### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by manfredt27**
This feature replaces the change background button and next button with foundation icons

### CODE REVIEW

**Comment by alvarezloaiciga** [comment]
I am ok with this, @BrayanZ ?

**Comment by BrayanZ** [comment]
seems good, but do we really need all the svg files? wouldn't it work just with the font files?

**Comment by alvarezloaiciga** [comment]
I don't think so: http://zurb.com/playground/foundation-icon-fonts-3, but we should probably try to use them via bower: http://foundation.zurb.com/forum/posts/12670-foundation-icon-fonts-via-bower-help

**Comment by manfredt27** [comment]
Run `bower install` in order to make the changes valid

**Comment by alvarezloaiciga** [comment]
wow that looks good! :)

**Pull request merged**
