### PR TITLE
Refactor forms to make them more generic

### PR DESCRIPTION
**Pull request by manfredt27**
In these feature, we change the configuration of the forms by adding the `previous`, `next` and `footer` attributes to each method, instead of injecting them directly into the html (jade) files. This facilitates future changes and introductions of new methods.

### CODE REVIEW

**Comment by alvarezloaiciga** [comment]
I am seeing a lot of duplicated code now, it feels like all the methods' htmls are the same, the only difference is in the form.

**Comment by manfredt27** [comment]
The original idea was to take the next, previous and watch buttons, along with the footer out from the individual files and into `method.jade`. But since the `ui-view` uses a separate instance of the `MethodsController` it didn't work as expected.

**Comment by alvarezloaiciga** [comment]
It feels like it is not the responsibility of the method to know which is the previous and the next method

**Comment by manfredt27** [comment]
Then how could we reach the objective of minimizing the duplicated code? Maybe a sorted list of the methods as a global variable?

**Comment by alvarezloaiciga** [comment]
You can probably try with a directive that lets you do something like:

``` html
<uvp-method method="this">
  <form>
  </form>
</uvp-method>
```

**Comment by BrayanZ** [comment]
What I suggested was to assign an order data attribute directly to the states, and build a service who would be the one in charge for the next and previous states. So all the responsibility is in a separate service.

**Pull request merged**
