### PR TITLE
Add footer

### PR DESCRIPTION
**Pull request by manfredt27**
Added method name footer and refactored to jade

### CODE REVIEW

**Comment by alvarezloaiciga** [comment]
Can you add an screenshot to see how it looks like?

**Comment by manfredt27** [comment]
screenshot from 2015-04-20 17 25 23

**Comment by alvarezloaiciga** [comment]
add some space in the right side

**Comment by manfredt27** [comment]
Like this??
screenshot from 2015-04-21 08 16 35

**Comment by manfredt27** [comment]
Adjusted bottom margin
screenshot from 2015-04-21 08 38 31

**Comment by manfredt27** [comment]
Fixed responsive margins
screenshot from 2015-04-21 09 15 27

**Pull request merged**
