### PR TITLE
Fix tooltips to make them appear only once

### PR DESCRIPTION
**Pull request by manfredt27**
Before:
image

After:
image

### CODE REVIEW

**Comment by alvarezloaiciga** [comment]
We should change the `example` orange color it's hard to read... maybe add a transparent black background

**Comment by manfredt27** [comment]
It only turns orange on mouse-over, it's normally white. Maybe change it to a shade of gray?

**Comment by manfredt27** [comment]
@alvarezloaiciga  like this?
image

**Comment by manfredt27** [comment]
@alvarezloaiciga @BrayanZ  what do you think of that color? It's the same one used with the icons on hover

**Comment by BrayanZ** [comment]
I prefer the other way around, make it greyish and white on the hover.

**Comment by manfredt27** [comment]
@BrayanZ The same with the icons then?

**Comment by alvarezloaiciga** [comment]
need to merge develop into this branch

**Comment by manfredt27** [comment]
Working on it

**Comment by manfredt27** [comment]
@alvarezloaiciga  Done

**Pull request merged**
